#!/usr/bin/env python3
"""
Module to describe characters from an audiobook using an LLM.
Reads characters from a characters.json file (generated by analyze_chapters.py)
and generates detailed descriptions for each character.
"""
import argparse
import glob
import json
import os
import re
import sys
from pathlib import Path
from openai import OpenAI
import requests
from bs4 import BeautifulSoup


# Default prompt for character description
CHARACTER_DESCRIPTION_PROMPT = """
You are an expert voice actor and audiobook narrator. Your task is to create unique voice profiles for characters based on their names and the context in which they appear in an audiobook.

For each character, provide a detailed voice profile that includes:
1. **Gender first**: Start with "Male" or "Female" (e.g., "Male", "Female")
2. **Age range**: Young adult, middle-aged, elderly, teenager, etc.
3. **Emotional base state**: Confident, nervous, authoritative, meek, playful, etc.
4. **Accent**: Regional (Southern drawl, Boston accent, British RP), socio-economic (posh, working-class), or neutral
5. **Speaking style**: Fast/talkative, slow/deliberate, formal/informal, gruff/smooth, etc.
6. **Unique vocal characteristics**: Any notable speech patterns, quirks, or distinctive features

Format your response as a JSON object where keys are character names and values are voice profiles.
Each description MUST begin with "Male" or "Female" followed by the age and other characteristics.
The description should be a single concise paragraph that illustrates how the character sounds when speaking.

Example format:
Male, elderly farmer with a meek and rustic lisp, speaks slowly with a drawl. His voice carries the weariness of decades on the land, often pausing mid-sentence as if remembering something.

Another example:
Female, mid-30s detective with a sharp, no-nonsense tone. She speaks in quick, clipped sentences with a slight Chicago accent, exuding quiet authority and weary skepticism.
"""


def get_characters_from_map_files(chapters_dir: Path) -> list:
    """Extract unique character names from map.json files.

    Args:
        chapters_dir: Path to the directory containing chapter map files

    Returns:
        Sorted list of unique character names
    """
    characters = set()

    map_files = glob.glob(str(chapters_dir / "*.map.json"))
    for map_file in map_files:
        try:
            with open(map_file, "r", encoding="utf-8") as f:
                data = json.load(f)
            character_map = data[0] if isinstance(data, list) and len(data) > 0 else data.get("character_map", {})
            if isinstance(character_map, dict):
                for char_name in character_map.values():
                    if isinstance(char_name, str):
                        characters.add(char_name)
        except Exception:
            pass

    return sorted(list(characters))


def load_characters(characters_file: str) -> list:
    """Load characters from a JSON file."""
    with open(characters_file, 'r', encoding='utf-8') as f:
        data = json.load(f)
    return data.get('characters', [])


def compare_characters(character_name: str, other_character: str) -> bool:
    """Check if two characters are likely the same based on name similarity.

    Only matches when one name contains the other as a complete word/token
    (separated by spaces on both sides), or exact match.
    """
    if character_name == other_character:
        return True

    lower1, lower2 = character_name.lower(), other_character.lower()

    # Check if one contains the other as a complete word (space-separated)
    # This catches "John Smith" containing "John" but not "Ara" containing "A"
    if f" {lower1} " in f" {lower2} " or f" {lower2} " in f" {lower1} ":
        return True

    # Also check prefix/suffix with space boundaries
    # e.g., "John" matches "John Smith" but not "Johnson"
    # Use shorter/longer to handle both directions properly
    shorter, longer = (lower1, lower2) if len(lower1) < len(lower2) else (lower2, lower1)
    if longer.startswith(shorter + " ") or longer.endswith(" " + shorter):
        return True

    return False


def find_duplicate_characters(characters: list) -> dict:
    """Find groups of duplicate characters based on name similarity.

    Returns a dict mapping canonical character name to list of duplicate names.
    """
    canonical_to_duplicates: dict = {}

    for char in characters:
        if char == "narrator":
            continue

        found_canonical = None
        for canonical in canonical_to_duplicates.keys():
            if compare_characters(char, canonical):
                found_canonical = canonical
                break

        if found_canonical:
            canonical_to_duplicates[canonical].append(char)
        else:
            canonical_to_duplicates[char] = []

    # Filter out entries with no duplicates
    return {k: v for k, v in canonical_to_duplicates.items() if v}


def create_duplicate_replacement_map(duplicates: dict) -> dict:
    """Create a mapping from each duplicate name to its canonical name.

    Args:
        duplicates: Dict mapping canonical name to list of duplicate names

    Returns:
        Dict mapping duplicate character names to their canonical name
    """
    replacement_map = {}
    for canonical, duplicates_list in duplicates.items():
        for dup_name in duplicates_list:
            replacement_map[dup_name] = canonical
    return replacement_map


def deduplicate_descriptions(descriptions: dict, duplicates: dict, verbose: bool = False) -> dict:
    """Deduplicate character descriptions based on duplicate character mappings.

    For each group of duplicate characters:
    - Keep the canonical character's description
    - Add "See <canonical> (same character)." for duplicates

    Args:
        descriptions: Dict mapping character names to their descriptions
        duplicates: Dict mapping canonical name to list of duplicate names
        verbose: Enable verbose output

    Returns:
        Dict with duplicates replaced by references to canonical characters
    """
    deduped = descriptions.copy()

    for canonical, duplicates_list in duplicates.items():
        # Add references for duplicates
        for dup_name in duplicates_list:
            if dup_name in descriptions:
                if verbose:
                    print(f"Marking '{dup_name}' as duplicate of '{canonical}'")
                deduped[dup_name] = f"See {canonical} (same character)."
            else:
                if verbose:
                    print(f"Duplicate '{dup_name}' not found in descriptions")

    return deduped


def load_chapter_text(chapter_file: str) -> str:
    """Load text from a chapter file."""
    with open(chapter_file, 'r', encoding='utf-8') as f:
        return f.read()


def find_chapters_with_character(chapter_texts: list, chapter_files: list, character_name: str) -> list:
    """Find chapters where a character is mentioned.

    Args:
        chapter_texts: List of chapter text content
        chapter_files: List of chapter file paths (in matching order)
        character_name: The character name to search for

    Returns:
        List of (chapter_file, chapter_text) tuples where character appears
    """
    chapters_with_char = []
    char_lower = character_name.lower()

    for text, filepath in zip(chapter_texts, chapter_files):
        if char_lower in text.lower():
            chapters_with_char.append((filepath, text))

    return chapters_with_char


def lookup_character_on_wiki(character_name: str, wiki_url_template: str = "") -> str:
    """Look up a character on a wiki for additional context.

    Args:
        character_name: The name of the character to look up
        wiki_url_template: URL template with {name} placeholder for the character name

    Returns:
        A string with biographical information from the wiki, or empty string if not found
    """
    # Format the URL with the character name
    url = wiki_url_template.format(name=character_name.replace(" ", "_"))

    try:
        headers = {"User-Agent": "Mozilla/5.0 (Audiobook Character Describer)"}
        response = requests.get(url, headers=headers, timeout=10)
        response.raise_for_status()

        soup = BeautifulSoup(response.content, "html.parser")

        # Check if it's a disambiguation page or doesn't exist
        content = soup.find("div", class_="mw-parser-output")
        if not content:
            return ""

        # Get the first paragraph (usually the most relevant)
        first_para = content.find("p")
        if first_para:
            text = first_para.get_text(strip=True)
            # Clean up citation brackets like [1], [2], etc.
            text = re.sub(r'\[\d+\]', '', text)
            return text[:1000]  # Limit to first 1000 chars

    except requests.RequestException:
        pass

    return ""


def build_character_context(characters: list, chapter_texts: list, chapter_files: list = [], wiki_url_template: str = "") -> str:
    """Build context string with character names and their appearances.

    Args:
        characters: List of character names
        chapter_texts: List of chapter text content
        chapter_files: List of chapter file paths (used for finding relevant chapters)
        wiki_url_template: Optional URL template for wiki lookup (with {name} placeholder)

    Returns:
        Context string for the LLM prompt
    """
    context = "Characters to describe:\n"
    for char in characters:
        context += f"- {char}\n"

    # Add wiki lookup context if enabled
    if wiki_url_template:
        context += "\n\nAdditional context from wiki:\n"
        for char in characters:
            wiki_info = lookup_character_on_wiki(char, wiki_url_template)
            if wiki_info:
                context += f"--- {char} ---\n{wiki_info}\n\n"

    # Build character-specific context using relevant chapters
    if chapter_files and len(chapter_files) == len(chapter_texts):
        context += "\n\nRelevant dialogue and context from the book:\n"
        for char in characters:
            relevant_chapters = find_chapters_with_character(chapter_texts, chapter_files, char)
            if relevant_chapters:
                context += f"\n--- {char} Context ---\n"
                # Use up to 2 most relevant chapters, first 800 chars each
                for filepath, text in relevant_chapters[:2]:
                    context += f"[From {filepath.name}]\n"
                    context += text[:800] + "\n\n"
    else:
        # Fallback to first 3 chapters for all characters
        context += "\n\nRelevant dialogue and context from the book:\n"
        for i, text in enumerate(chapter_texts[:3]):
            context += f"--- Chapter {i+1} Excerpt ---\n"
            context += text[:1000] + "\n\n"
    return context


def describe_character(client: OpenAI, model: str, character: str, context: str) -> str:
    """Ask the LLM to describe a single character."""
    messages = [
        {"role": "system", "content": CHARACTER_DESCRIPTION_PROMPT},
        {"role": "user", "content": f"Describe this character in detail:\n\nCharacter name: {character}\n\nContext:\n{context}"}
    ]

    try:
        response = client.chat.completions.create(
            model=model,
            messages=messages,
            temperature=0.7,
        )
        return response.choices[0].message.content
    except Exception as e:
        return f"Error describing character: {e}"


def describe_all_characters(client: OpenAI, model: str, characters: list, context: str) -> dict:
    """Ask the LLM to describe all characters at once."""
    messages = [
        {"role": "system", "content": CHARACTER_DESCRIPTION_PROMPT},
        {"role": "user", "content": f"Describe all these characters in detail. Return a JSON object with character names as keys and descriptions as values.\n\nCharacters:\n{chr(10).join(characters)}\n\nContext:\n{context}"}
    ]

    try:
        response = client.chat.completions.create(
            model=model,
            messages=messages,
            temperature=0.7,
        )
        content = response.choices[0].message.content
        # Try to parse JSON from response
        try:
            # Remove markdown code blocks if present
            if content.startswith('```json'):
                content = content[7:]
            if content.startswith('```'):
                content = content[3:]
            if content.endswith('```'):
                content = content[:-3]
            content = content.strip()
            return json.loads(content)
        except json.JSONDecodeError:
            # If parsing fails, return raw content
            return {char: content for char in characters}
    except Exception as e:
        print(f"Error describing characters: {e}", file=sys.stderr)
        return {}


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Describe characters from an audiobook using an LLM"
    )
    parser.add_argument(
        "characters_file",
        nargs="?",
        default="characters.json",
        help="Path to characters.json file (generated by analyze_chapters.py)"
    )
    parser.add_argument(
        "chapters_dir",
        nargs="?",
        default="chapters",
        help="Directory containing chapter text files"
    )
    parser.add_argument(
        "--verbose", "-v",
        action="store_true",
        help="Enable verbose printing for debug."
    )
    parser.add_argument(
        "--api_key",
        "-k",
        metavar="API_KEY",
        default="lm-studio",
        help="Provide custom API key."
    )
    parser.add_argument(
        "--port",
        "-p",
        metavar="PORT",
        default="1234",
        help="Provide custom port for inference."
    )
    parser.add_argument(
        "--model",
        "-m",
        default="local-model",
        help="Model name to use for inference."
    )
    parser.add_argument(
        "--single-character",
        metavar="CHARACTER",
        help="Describe a single specific character."
    )
    parser.add_argument(
        "--wiki-url",
        metavar="URL",
        dest="wiki_url_template",
        help="Enable lookup on wiki using URL template (use {name} placeholder for character name)."
    )
    parser.add_argument(
        "--output-dir",
        metavar="DIR",
        dest="output_dir",
        default=".",
        help="Directory to save output files (characters_descriptions.json and duplicate_replacement_map.json)."
    )
    args = parser.parse_args()

    client = OpenAI(
        base_url=f"http://localhost:{args.port}/v1",
        api_key=args.api_key
    )

    # Load characters from characters.json or extract from map files
    if os.path.exists(args.characters_file):
        characters = load_characters(args.characters_file)
        print(f"Loaded {len(characters)} characters from {args.characters_file}")
    else:
        # Try to extract characters from map files in the output_dir (chapters directory)
        chapters_path = Path(args.output_dir)
        if chapters_path.is_dir():
            characters = get_characters_from_map_files(chapters_path)
            print(f"Extracted {len(characters)} characters from map files in {args.output_dir}")
        else:
            print(f"Characters file not found: {args.characters_file}", file=sys.stderr)
            sys.exit(1)

    # Load chapter texts for context
    chapters_dir = Path(args.chapters_dir)
    chapter_texts = []
    chapter_files = []
    if chapters_dir.is_dir():
        chapter_files = sorted(chapters_dir.glob("chapter_*.txt"))
        for chapter_file in chapter_files:
            chapter_texts.append(load_chapter_text(str(chapter_file)))
        if args.verbose:
            print(f"Loaded {len(chapter_texts)} chapter files for context")

    # Build context
    context = build_character_context(characters, chapter_texts, chapter_files, args.wiki_url_template)

    # Describe characters
    if args.single_character:
        if args.single_character not in characters:
            print(f"Character '{args.single_character}' not found in characters list.", file=sys.stderr)
            sys.exit(1)
        if args.verbose:
            print(f"Describing single character: {args.single_character}")
        description = describe_character(client, args.model, args.single_character, context)
        print(f"\nDescription for '{args.single_character}':")
        print(description)
    else:
        if args.verbose:
            print(f"Describing {len(characters)} characters...")

        # Find duplicate characters before describing
        duplicates = find_duplicate_characters(characters)
        if args.verbose and duplicates:
            print(f"Found duplicate character names: {duplicates}")

        # Create a map from duplicate names to canonical names
        duplicate_replacement_map = create_duplicate_replacement_map(duplicates)
        if args.verbose and duplicate_replacement_map:
            print(f"Duplicate replacement map: {duplicate_replacement_map}")

        # Get list of canonical characters (exclude duplicates)
        canonical_characters = [
            char for char in characters
            if char not in duplicate_replacement_map
        ]
        if args.verbose:
            print(f"Canonical characters to describe: {canonical_characters}")

        # Describe only canonical characters
        descriptions = describe_all_characters(client, args.model, canonical_characters, context)

        deduped_descriptions = descriptions

        # Save duplicate replacement map to file
        replacement_map_file = os.path.join(args.output_dir, "duplicate_replacement_map.json")
        with open(replacement_map_file, 'w', encoding='utf-8') as f:
            json.dump(duplicate_replacement_map, f, indent=2, ensure_ascii=False)
        if args.verbose:
            print(f"Duplicate replacement map saved to: {replacement_map_file}")

        # Save results (replacing em dashes with regular hyphens)
        output_file = os.path.join(args.output_dir, "characters_descriptions.json")
        with open(output_file, 'w', encoding='utf-8') as f:
            # Convert descriptions to JSON string and replace em dash with hyphen
            json_content = json.dumps(deduped_descriptions, indent=2, ensure_ascii=False)
            json_content = json_content.replace('\u2014', '-')
            f.write(json_content)
        print(f"\nCharacter descriptions saved to: {output_file}")

        # Print summary
        print("\nCharacter descriptions generated:")
        for char, desc in deduped_descriptions.items():
            # Show first line of description
            first_line = desc.split('\n')[0][:80]
            # Handle Windows console encoding issues
            try:
                print(f"  - {char}: {first_line}...")
            except UnicodeEncodeError:
                # Fallback for Windows console
                safe_line = first_line.encode('utf-8', errors='replace').decode('utf-8')
                print(f"  - {char}: {safe_line}...")


# ============================================================================
# MODULE FUNCTIONS FOR GRADIO INTERFACE
# ============================================================================

from typing import Dict, Optional, Tuple


def describe_characters_in_dir(
    output_dir: str,
    api_key: str,
    port: str,
    model: str = "local-model",
    single_character: Optional[str] = None,
    verbose: bool = False
) -> Tuple[str, Dict[str, str]]:
    """Describe characters in a directory using LLM.

    This is a simplified interface for calling character description directly
    from the Gradio UI without subprocess.

    Args:
        output_dir: Directory containing chapter map files and chapter text files
        api_key: API key for the LLM (can be any string for LM Studio)
        port: Port for the LLM inference
        model: Model name to use for inference
        single_character: Describe only one specific character
        verbose: Print verbose output

    Returns:
        Tuple of (status_message, character_descriptions)
    """
    try:
        from pathlib import Path
        from openai import OpenAI

        chapters_path = Path(output_dir)

        # Load characters from map files
        characters = get_characters_from_map_files(chapters_path)

        if not characters:
            return "No characters found in map files.", {}

        if single_character:
            if single_character not in characters:
                return f"Character '{single_character}' not found.", {}
            characters = [single_character]

        # Load chapter texts for context
        chapter_texts = []
        chapter_files = []
        if chapters_path.is_dir():
            chapter_files = sorted(chapters_path.glob("chapter_*.txt"))
            for chapter_file in chapter_files:
                chapter_texts.append(load_chapter_text(str(chapter_file)))
            if verbose:
                print(f"Loaded {len(chapter_texts)} chapter files for context")

        # Build context
        context = build_character_context(characters, chapter_texts, chapter_files, "")

        # Initialize client
        client = OpenAI(
            base_url=f"http://localhost:{port}/v1",
            api_key=api_key
        )

        # Find duplicate characters before describing
        duplicates = find_duplicate_characters(characters)
        if verbose and duplicates:
            print(f"Found duplicate character names: {duplicates}")

        # Create a map from duplicate names to canonical names
        duplicate_replacement_map = create_duplicate_replacement_map(duplicates)
        if verbose and duplicate_replacement_map:
            print(f"Duplicate replacement map: {duplicate_replacement_map}")

        # Get list of canonical characters (exclude duplicates)
        canonical_characters = [
            char for char in characters
            if char not in duplicate_replacement_map
        ]
        if verbose:
            print(f"Canonical characters to describe: {canonical_characters}")

        # Describe only canonical characters
        descriptions = describe_all_characters(client, model, canonical_characters, context)

        deduped_descriptions = descriptions

        # Save duplicate replacement map to file
        replacement_map_file = os.path.join(output_dir, "duplicate_replacement_map.json")
        with open(replacement_map_file, 'w', encoding='utf-8') as f:
            json.dump(duplicate_replacement_map, f, indent=2, ensure_ascii=False)

        # Save results (replacing em dashes with regular hyphens)
        output_file = os.path.join(output_dir, "characters_descriptions.json")
        with open(output_file, 'w', encoding='utf-8') as f:
            # Convert descriptions to JSON string and replace em dash with hyphen
            json_content = json.dumps(deduped_descriptions, indent=2, ensure_ascii=False)
            json_content = json_content.replace('\u2014', '-')
            f.write(json_content)

        if verbose:
            print(f"Character descriptions saved to: {output_file}")

        return f"Successfully described {len(deduped_descriptions)} characters.", deduped_descriptions

    except Exception as e:
        import traceback
        error_msg = f"Error describing characters: {str(e)}\n{traceback.format_exc()}"
        if verbose:
            print(error_msg)
        return error_msg, {}


if __name__ == "__main__":
    main()