#!/usr/bin/env python3
"""
Module to describe characters from an audiobook using an LLM.
Reads characters from a characters.json file (generated by analyze_chapters.py)
and generates detailed descriptions for each character.
"""
import argparse
import json
import os
import sys
from pathlib import Path
from openai import OpenAI

# Default prompt for character description
CHARACTER_DESCRIPTION_PROMPT = """
You are an expert voice actor and audiobook narrator. Your task is to create unique voice profiles for characters based on their names and the context in which they appear in an audiobook.

For each character, provide a detailed voice profile that includes:
1. **Gender first**: Start with "Male" or "Female" (e.g., "Male", "Female")
2. **Age range**: Young adult, middle-aged, elderly, teenager, etc.
3. **Emotional base state**: Confident, nervous, authoritative, meek, playful, etc.
4. **Accent**: Regional (Southern drawl, Boston accent, British RP), socio-economic (posh, working-class), or neutral
5. **Speaking style**: Fast/talkative, slow/deliberate, formal/informal, gruff/smooth, etc.
6. **Unique vocal characteristics**: Any notable speech patterns, quirks, or distinctive features

Format your response as a JSON object where keys are character names and values are their voice profiles.
Each description MUST begin with "Male" or "Female" followed by the age and other characteristics.
The description should be a single concise paragraph that illustrates how the character sounds when speaking.

Example format:
Male, elderly farmer with a meek and rustic lisp, speaks slowly with a drawl. His voice carries the weariness of decades on the land, often pausing mid-sentence as if remembering something.

Another example:
Female, mid-30s detective with a sharp, no-nonsense tone. She speaks in quick, clipped sentences with a slight Chicago accent, exuding quiet authority and weary skepticism.
"""


def load_characters(characters_file: str) -> list:
    """Load characters from a JSON file."""
    with open(characters_file, 'r', encoding='utf-8') as f:
        data = json.load(f)
    return data.get('characters', [])


def compare_characters(character_name: str, other_character: str) -> bool:
    """Check if two characters are likely the same based on name similarity.

    Only matches when one name contains the other as a complete word/token
    (separated by spaces on both sides), or exact match.
    """
    if character_name == other_character:
        return True

    lower1, lower2 = character_name.lower(), other_character.lower()

    # Check if one contains the other as a complete word (space-separated)
    # This catches "John Smith" containing "John" but not "Ara" containing "A"
    if f" {lower1} " in f" {lower2} " or f" {lower2} " in f" {lower1} ":
        return True

    # Also check prefix/suffix with space boundaries
    # e.g., "John" matches "John Smith" but not "Johnson"
    if lower2.startswith(lower1 + " ") or lower1.startswith(lower2 + " "):
        return True
    if lower2.endswith(" " + lower1) or lower1.endswith(" " + lower2):
        return True

    return False


def find_duplicate_characters(characters: list) -> dict:
    """Find groups of duplicate characters based on name similarity.

    Returns a dict mapping canonical character name to list of duplicate names.
    """
    canonical_to_duplicates: dict = {}

    for char in characters:
        if char == "narrator":
            continue

        found_canonical = None
        for canonical in canonical_to_duplicates.keys():
            if compare_characters(char, canonical):
                found_canonical = canonical
                break

        if found_canonical:
            canonical_to_duplicates[canonical].append(char)
        else:
            canonical_to_duplicates[char] = []

    # Filter out entries with no duplicates
    return {k: v for k, v in canonical_to_duplicates.items() if v}


def deduplicate_descriptions(descriptions: dict, duplicates: dict, verbose: bool = False) -> dict:
    """Deduplicate character descriptions based on duplicate character mappings.

    For each group of duplicate characters:
    - Keep the canonical character's description
    - Add "See <canonical> (same character)." for duplicates

    Args:
        descriptions: Dict mapping character names to their descriptions
        duplicates: Dict mapping canonical name to list of duplicate names
        verbose: Enable verbose output

    Returns:
        Dict with duplicates replaced by references to canonical characters
    """
    deduped = descriptions.copy()

    for canonical, duplicates_list in duplicates.items():
        # Add references for duplicates
        for dup_name in duplicates_list:
            if dup_name in descriptions:
                if verbose:
                    print(f"Marking '{dup_name}' as duplicate of '{canonical}'")
                deduped[dup_name] = f"See {canonical} (same character)."
            else:
                if verbose:
                    print(f"Duplicate '{dup_name}' not found in descriptions")

    return deduped


def load_chapter_text(chapter_file: str) -> str:
    """Load text from a chapter file."""
    with open(chapter_file, 'r', encoding='utf-8') as f:
        return f.read()


def build_character_context(characters: list, chapter_texts: list) -> str:
    """Build context string with character names and their appearances."""
    context = "Characters to describe:\n"
    for char in characters:
        context += f"- {char}\n"

    context += "\n\nRelevant dialogue and context from the book:\n"
    for i, text in enumerate(chapter_texts[:3]):  # Use first 3 chapters for context
        context += f"--- Chapter {i+1} Excerpt ---\n"
        context += text[:1000]  # First 1000 chars of each chapter
        context += "\n\n"
    return context


def describe_character(client: OpenAI, model: str, character: str, context: str) -> str:
    """Ask the LLM to describe a single character."""
    messages = [
        {"role": "system", "content": CHARACTER_DESCRIPTION_PROMPT},
        {"role": "user", "content": f"Describe this character in detail:\n\nCharacter name: {character}\n\nContext:\n{context}"}
    ]

    try:
        response = client.chat.completions.create(
            model=model,
            messages=messages,
            temperature=0.7,
        )
        return response.choices[0].message.content
    except Exception as e:
        return f"Error describing character: {e}"


def describe_all_characters(client: OpenAI, model: str, characters: list, context: str) -> dict:
    """Ask the LLM to describe all characters at once."""
    messages = [
        {"role": "system", "content": CHARACTER_DESCRIPTION_PROMPT},
        {"role": "user", "content": f"Describe all these characters in detail. Return a JSON object with character names as keys and descriptions as values.\n\nCharacters:\n{chr(10).join(characters)}\n\nContext:\n{context}"}
    ]

    try:
        response = client.chat.completions.create(
            model=model,
            messages=messages,
            temperature=0.7,
        )
        content = response.choices[0].message.content
        # Try to parse JSON from response
        try:
            # Remove markdown code blocks if present
            if content.startswith('```json'):
                content = content[7:]
            if content.startswith('```'):
                content = content[3:]
            if content.endswith('```'):
                content = content[:-3]
            content = content.strip()
            return json.loads(content)
        except json.JSONDecodeError:
            # If parsing fails, return raw content
            return {char: content for char in characters}
    except Exception as e:
        print(f"Error describing characters: {e}", file=sys.stderr)
        return {}


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Describe characters from an audiobook using an LLM"
    )
    parser.add_argument(
        "characters_file",
        nargs="?",
        default="characters.json",
        help="Path to characters.json file (generated by analyze_chapters.py)"
    )
    parser.add_argument(
        "chapters_dir",
        nargs="?",
        default="chapters",
        help="Directory containing chapter text files"
    )
    parser.add_argument(
        "--verbose", "-v",
        action="store_true",
        help="Enable verbose printing for debug."
    )
    parser.add_argument(
        "-api_key",
        metavar="lm-studio",
        default="lm-studio",
        help="Provide custom API key."
    )
    parser.add_argument(
        "-port",
        metavar="1234",
        default="1234",
        help="Provide custom port for inference."
    )
    parser.add_argument(
        "-model",
        default="local-model",
        help="Model name to use for inference."
    )
    parser.add_argument(
        "--single-character",
        metavar="CHARACTER",
        help="Describe a single specific character."
    )
    args = parser.parse_args()

    client = OpenAI(
        base_url=f"http://localhost:{args.port}/v1",
        api_key=args.api_key
    )

    # Load characters
    if not os.path.exists(args.characters_file):
        print(f"Characters file not found: {args.characters_file}", file=sys.stderr)
        sys.exit(1)

    characters = load_characters(args.characters_file)
    print(f"Loaded {len(characters)} characters from {args.characters_file}")

    # Load chapter texts for context
    chapters_dir = Path(args.chapters_dir)
    chapter_texts = []
    if chapters_dir.is_dir():
        chapter_files = sorted(chapters_dir.glob("chapter_*.txt"))
        for chapter_file in chapter_files:
            chapter_texts.append(load_chapter_text(str(chapter_file)))
        if args.verbose:
            print(f"Loaded {len(chapter_texts)} chapter files for context")

    # Build context
    context = build_character_context(characters, chapter_texts)

    # Describe characters
    if args.single_character:
        if args.single_character not in characters:
            print(f"Character '{args.single_character}' not found in characters list.", file=sys.stderr)
            sys.exit(1)
        if args.verbose:
            print(f"Describing single character: {args.single_character}")
        description = describe_character(client, args.model, args.single_character, context)
        print(f"\nDescription for '{args.single_character}':")
        print(description)
    else:
        if args.verbose:
            print(f"Describing {len(characters)} characters...")

        # Find duplicate characters before describing
        duplicates = find_duplicate_characters(characters)
        if args.verbose and duplicates:
            print(f"Found duplicate character names: {duplicates}")

        # Describe all characters
        descriptions = describe_all_characters(client, args.model, characters, context)

        # Deduplicate descriptions based on name similarity
        deduped_descriptions = deduplicate_descriptions(descriptions, duplicates, args.verbose)

        # Save results (replacing em dashes with regular hyphens)
        output_file = "characters_descriptions.json"
        with open(output_file, 'w', encoding='utf-8') as f:
            # Convert descriptions to JSON string and replace em dash with hyphen
            json_content = json.dumps(deduped_descriptions, indent=2, ensure_ascii=False)
            json_content = json_content.replace('\u2014', '-')
            f.write(json_content)
        print(f"\nCharacter descriptions saved to: {output_file}")

        # Print summary
        print("\nCharacter descriptions generated:")
        for char, desc in deduped_descriptions.items():
            # Show first line of description
            first_line = desc.split('\n')[0][:80]
            print(f"  - {char}: {first_line}...")


if __name__ == "__main__":
    main()