#!/usr/bin/env python3
"""
Module to describe characters from an audiobook using an LLM.
Reads characters from a characters.json file (generated by analyze_chapters.py)
and generates detailed descriptions for each character.
"""
import argparse
import glob
import json
import os
import re
import sys
from pathlib import Path
from typing import Dict, List, Optional, Tuple
from openai import OpenAI
import requests
from bs4 import BeautifulSoup

from config import LLM_SETTINGS, OUTPUT_DIR
from utils import get_llm_client, compare_characters, get_characters_from_map_files

# Module-level cache for chapter text content
_chapter_text_cache: Dict[str, Dict[Path, str]] = {}


# Default prompt for character description
CHARACTER_DESCRIPTION_PROMPT = """
You are an expert voice actor and audiobook narrator. Your task is to create short, distinctive voice profiles for characters.

Focus on the most distinctive, memorable traits that would help a professional voice actor embody the character.

Provide the following information in the description:
gender and age.
speed, volume,  clarity, and tone of voice.

#Example format for a male character:
30 year old Man.
Fast-paced delivery with deliberate pauses for dramatic effect.
Loud and projecting, increasing notably during moments of praise and announcements.
Highly articulate and distinct pronunciation.
Upbeat, authoritative, and performative.

#Example format for a female character:
30 year old Woman.
Starts measured, then accelerates rapidly during emotional outburst.
Begins conversational, escalates quickly to loud and forceful.
Slightly slurred pronunciation.
Initially accepting, becomes sharply accusatory and confrontational.
"""

# get_characters_from_map_files is now imported from utils (uses glob with sorted output)


def load_characters(characters_file: str) -> list:
    """Load characters from a JSON file."""
    with open(characters_file, 'r', encoding='utf-8') as f:
        data = json.load(f)
    return data.get('characters', [])


# compare_characters is now imported from utils (uses simple substring matching)


def find_duplicate_characters(characters: list) -> dict:
    """Find groups of duplicate characters based on name similarity.

    Returns a dict mapping canonical character name to list of duplicate names.
    """
    canonical_to_duplicates: dict = {}

    for char in characters:
        if char == "narrator":
            continue

        found_canonical = None
        for canonical in canonical_to_duplicates.keys():
            if compare_characters(char, canonical):
                found_canonical = canonical
                break

        if found_canonical:
            canonical_to_duplicates[canonical].append(char)
        else:
            canonical_to_duplicates[char] = []

    # Filter out entries with no duplicates
    return {k: v for k, v in canonical_to_duplicates.items() if v}


def create_duplicate_replacement_map(duplicates: dict) -> dict:
    """Create a mapping from each duplicate name to its canonical name.

    Args:
        duplicates: Dict mapping canonical name to list of duplicate names

    Returns:
        Dict mapping duplicate character names to their canonical name
    """
    replacement_map = {}
    for canonical, duplicates_list in duplicates.items():
        for dup_name in duplicates_list:
            replacement_map[dup_name] = canonical
    return replacement_map


def deduplicate_descriptions(descriptions: dict, duplicates: dict, verbose: bool = False) -> dict:
    """Deduplicate character descriptions based on duplicate character mappings.

    For each group of duplicate characters:
    - Keep the canonical character's description
    - Add "See <canonical> (same character)." for duplicates

    Args:
        descriptions: Dict mapping character names to their descriptions
        duplicates: Dict mapping canonical name to list of duplicate names
        verbose: Enable verbose output

    Returns:
        Dict with duplicates replaced by references to canonical characters
    """
    deduped = descriptions.copy()

    for canonical, duplicates_list in duplicates.items():
        # Add references for duplicates
        for dup_name in duplicates_list:
            if dup_name in descriptions:
                if verbose:
                    print(f"Marking '{dup_name}' as duplicate of '{canonical}'")
                deduped[dup_name] = f"See {canonical} (same character)."
            else:
                if verbose:
                    print(f"Duplicate '{dup_name}' not found in descriptions")

    return deduped


def load_chapter_text(chapter_file: str) -> str:
    """Load text from a chapter file."""
    with open(chapter_file, 'r', encoding='utf-8') as f:
        return f.read()


def load_chapter_texts_with_cache(chapters_dir: Path) -> Tuple[List[str], List[Path]]:
    """Load chapter texts with module-level caching.

    Args:
        chapters_dir: Path to the chapters directory

    Returns:
        Tuple of (list of chapter texts, list of chapter file paths)
    """
    chapters_dir_str = str(chapters_dir)

    # Check if we have cached data for this directory
    if chapters_dir_str in _chapter_text_cache:
        return _chapter_text_cache[chapters_dir_str]

    # Load and cache chapter texts
    chapter_files = sorted(chapters_dir.glob("chapter_*.txt"))
    chapter_texts = []

    for chapter_file in chapter_files:
        chapter_texts.append(load_chapter_text(str(chapter_file)))

    # Store in cache
    _chapter_text_cache[chapters_dir_str] = (chapter_texts, chapter_files)

    return chapter_texts, chapter_files


def find_chapters_with_character(chapter_texts: list, chapter_files: list, character_name: str) -> list:
    """Find chapters where a character is mentioned.

    Args:
        chapter_texts: List of chapter text content
        chapter_files: List of chapter file paths (in matching order)
        character_name: The character name to search for

    Returns:
        List of (chapter_file, chapter_text) tuples where character appears
    """
    chapters_with_char = []
    char_lower = character_name.lower()

    for text, filepath in zip(chapter_texts, chapter_files):
        if char_lower in text.lower():
            chapters_with_char.append((filepath, text))

    return chapters_with_char


def lookup_character_on_wiki(character_name: str, wiki_url_template: str = "") -> str:
    """Look up a character on a wiki for additional context.

    Args:
        character_name: The name of the character to look up
        wiki_url_template: URL template with {name} placeholder for the character name

    Returns:
        A string with biographical information from the wiki, or empty string if not found
    """
    # Format the URL with the character name
    url = wiki_url_template.format(name=character_name.replace(" ", "_"))

    try:
        headers = {"User-Agent": "Mozilla/5.0 (Audiobook Character Describer)"}
        response = requests.get(url, headers=headers, timeout=10)
        response.raise_for_status()

        soup = BeautifulSoup(response.content, "html.parser")

        # Check if it's a disambiguation page or doesn't exist
        content = soup.find("div", class_="mw-parser-output")
        if not content:
            return ""

        # Get the first paragraph (usually the most relevant)
        first_para = content.find("p")
        if first_para:
            text = first_para.get_text(strip=True)
            # Clean up citation brackets like [1], [2], etc.
            text = re.sub(r'\[\d+\]', '', text)
            return text[:1000]  # Limit to first 1000 chars

    except requests.RequestException:
        pass

    return ""


def load_chapter_lines(chapter_file: str) -> list:
    """Load a chapter file and return lines as a list (1-indexed for convenience).

    Args:
        chapter_file: Path to the chapter text file

    Returns:
        List of lines with empty string at index 0 for 1-indexed access
        (Line N: prefixes are stripped if present)
    """
    with open(chapter_file, 'r', encoding='utf-8') as f:
        lines = f.readlines()
    # Remove trailing newlines, strip "Line N: " prefix if present, and make 1-indexed
    cleaned_lines = ['']  # Empty string at index 0 for 1-indexed access
    for line in lines:
        line = line.rstrip('\n\r')
        # Strip "Line N: " prefix if present
        if line.startswith("Line"):
            match = re.match(r'^Line\s+\d+:\s*(.*)$', line)
            if match:
                line = match.group(1)
        cleaned_lines.append(line)
    return cleaned_lines


def extract_character_dialogue(chapters_dir: Path, character_name: str, max_examples: int = None) -> list:
    """Extract actual dialogue lines spoken by a character from map files.

    Args:
        chapters_dir: Path to the chapters directory
        character_name: The character name to extract dialogue for
        max_examples: Maximum number of dialogue examples to return (None = all lines)

    Returns:
        List of (chapter_name, dialogue_line) tuples
    """
    dialogue_examples = []
    char_lower = character_name.lower()

    # Get all map files sorted
    map_files = sorted([f for f in chapters_dir.glob("*.map.json")
                       if re.match(r"^chapter_\d+\.map\.json$", f.name)])

    for map_file in map_files:
        try:
            with open(map_file, "r", encoding="utf-8") as f:
                data = json.load(f)

            # Handle both list format [char_map, line_map] and dict format
            if isinstance(data, list) and len(data) >= 2:
                character_map = data[0]
                line_map = data[1]
            elif isinstance(data, dict):
                character_map = data.get("character_map", {})
                line_map = data.get("line_map", {})
            else:
                continue

            # Find the speaker key for this character
            character_speaker_key = None
            for speaker_key, char_name in character_map.items():
                if char_name.lower() == char_lower:
                    character_speaker_key = speaker_key
                    break

            if character_speaker_key is None:
                continue

            # Find all lines attributed to this character's speaker key
            character_lines = []
            for line_num_str, speaker_key_in_line in line_map.items():
                if str(speaker_key_in_line) == str(character_speaker_key):
                    character_lines.append(int(line_num_str))

            # Load chapter text and extract dialogue
            # Map files are named chapter_N.map.json, text files are chapter_N.txt
            # So we need to strip the ".map" suffix from the stem
            map_stem = map_file.stem  # e.g., "chapter_0.map"
            chapter_stem = map_stem.rsplit(".map", 1)[0]  # e.g., "chapter_0"
            chapter_txt_file = chapter_stem + ".txt"
            chapter_txt_path = chapters_dir / chapter_txt_file
            if chapter_txt_path.exists():
                lines = load_chapter_lines(str(chapter_txt_path))
                for line_num in sorted(character_lines):
                    if line_num < len(lines):
                        line_text = lines[line_num]
                        # Only include lines that look like dialogue (start with quote)
                        if line_text.strip().startswith('"'):
                            dialogue_examples.append((map_file.stem, line_text.strip()))
                            if max_examples is not None and len(dialogue_examples) >= max_examples:
                                break
        except Exception:
            continue

    return dialogue_examples


def build_character_context(characters: list, chapter_texts: list, chapter_files: list = [],
                           chapters_dir: Path = None, wiki_url_template: str = "") -> Tuple[str, list]:
    """Build context string with character names and their actual dialogue.

    Args:
        characters: List of character names
        chapter_texts: List of chapter text content (deprecated, kept for compatibility)
        chapter_files: List of chapter file paths (deprecated, kept for compatibility)
        chapters_dir: Path to chapters directory (preferred method)
        wiki_url_template: Optional URL template for wiki lookup (with {name} placeholder)

    Returns:
        Tuple of (context string, list of chapter-based dialogue messages)
    """
    context = "Characters to describe:\n"
    for char in characters:
        context += f"{char}\n"

    # # Add wiki lookup context if enabled
    # if wiki_url_template:
    #     context += "\n\nAdditional context from wiki:\n"
    #     for char in characters:
    #         wiki_info = lookup_character_on_wiki(char, wiki_url_template)
    #         if wiki_info:
    #             context += f"--- {char} ---\n{wiki_info}\n\n"

    # Build character-specific context using actual dialogue from map files
    context = "Character dialogue examples from the book:\n"
    chapter_messages = []

    if chapters_dir and chapters_dir.is_dir():
        for char in characters:
            if char == "narrator":
                continue
            dialogue_examples = extract_character_dialogue(chapters_dir, char, max_examples=None)
            if dialogue_examples:
                context += f"\n--- {char} ---\n"
                chapter_messages.append(f"Here is all the dialogue spoken by {char} from each chapter:\n")
                for chapter_name, dialogue_line in dialogue_examples:
                    context += f"{dialogue_line}\n"
                    chapter_messages.append(f"From {chapter_name}:\n{dialogue_line}")
            else:
                context += f"\n--- {char} ---\n(No direct dialogue found)\n"
    elif chapter_files and len(chapter_files) == len(chapter_texts):
        # Fallback to old method if chapters_dir not provided
        for char in characters:
            relevant_chapters = find_chapters_with_character(chapter_texts, chapter_files, char)
            if relevant_chapters:
                # context += f"\n--- {char} Context ---\n"
                for filepath, text in relevant_chapters[:2]:
                    # context += f"[From {filepath.name}]\n"
                    context += text[:800] + "\n"
    else:
        # Fallback to first 3 chapters for all characters
        for i, text in enumerate(chapter_texts[:3]):
            context += f"--- Chapter {i+1} Excerpt ---\n"
            context += text[:1000] + "\n\n"

    return context, chapter_messages


def describe_character(client: OpenAI, model: str, character: str, context: str, chapter_messages: list = None) -> str:
    """Ask the LLM to describe a single character.

    Args:
        client: OpenAI client instance
        model: Model name to use for inference
        character: Character name to describe
        context: Character description context string
        chapter_messages: Optional list of chapter-based dialogue messages
    """
    # System prompt first
    messages = [
        {"role": "system", "content": CHARACTER_DESCRIPTION_PROMPT},
    ]

    # Add chapter messages as separate user messages if provided
    if chapter_messages:
        for chapter_msg in chapter_messages:
            messages.append({"role": "user", "content": chapter_msg})

    # Final user message with the character to describe and summary context
    messages.append({"role": "user", "content": f"Describe this character in detail: {character} \n\nContext:\n{context}"})

    try:
        response = client.chat.completions.create(
            model=model,
            messages=messages
        )
        return response.choices[0].message.content
    except Exception as e:
        return f"Error describing character: {e}"


def describe_all_characters(client: OpenAI, model: str, characters: list, context: str) -> dict:
    """Ask the LLM to describe all characters at once."""
    # Build the user message
    user_message = f"Describe all these characters in detail. Return a JSON object with character names as keys and descriptions as values.\n\nCharacters:\n{chr(10).join(characters)}\n\nContext:\n{context}"

    messages = [
        {"role": "system", "content": CHARACTER_DESCRIPTION_PROMPT},
        {"role": "user", "content": user_message}
    ]

    # DEBUG: Save the context and messages to a file for debugging
    debug_output = {
        "model": model,
        "system_prompt": CHARACTER_DESCRIPTION_PROMPT,
        "characters": characters,
        "context": context,
    }
    with open("chapters/llm_character_description_debug.json", "w", encoding="utf-8") as f:
        json.dump(debug_output, f, indent=2, ensure_ascii=False)
    print("DEBUG: Saved LLM call context and messages to chapters/llm_character_description_debug.json")

    try:
        response = client.chat.completions.create(
            model=model,
            messages=messages
        )
        content = response.choices[0].message.content
        # Try to parse JSON from response
        try:
            # Remove markdown code blocks if present
            if content.startswith('```json'):
                content = content[7:]
            if content.startswith('```'):
                content = content[3:]
            if content.endswith('```'):
                content = content[:-3]
            content = content.strip()
            parsed = json.loads(content)

            # Validate that the response contains all expected character names
            # Check for at least one matching character name (case-insensitive)
            missing_chars = []
            for char in characters:
                char_lower = char.lower()
                found = any(k.lower() == char_lower for k in parsed.keys())
                if not found:
                    missing_chars.append(char)

            if missing_chars:
                # If we're missing character names, the LLM likely returned the example names
                # Instead of the actual character names - use fallback
                print(f"Warning: LLM response missing character names: {missing_chars}. Using fallback.")
                return {char: content for char in characters}

            return parsed
        except json.JSONDecodeError:
            # If parsing fails, return raw content
            return {char: content for char in characters}
    except Exception as e:
        print(f"Error describing characters: {e}", file=sys.stderr)
        return {}


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Describe characters from an audiobook using an LLM"
    )
    parser.add_argument(
        "characters_file",
        nargs="?",
        default="characters.json",
        help="Path to characters.json file (generated by analyze_chapters.py)"
    )
    parser.add_argument(
        "chapters_dir",
        nargs="?",
        default="chapters",
        help="Directory containing chapter text files"
    )
    parser.add_argument(
        "--verbose", "-v",
        action="store_true",
        help="Enable verbose printing for debug."
    )
    parser.add_argument(
        "--api_key",
        "-k",
        metavar="API_KEY",
        default=LLM_SETTINGS["api_key"],
        help="Provide custom API key."
    )
    parser.add_argument(
        "--port",
        "-p",
        metavar="PORT",
        default=LLM_SETTINGS["port"],
        help="Provide custom port for inference."
    )
    parser.add_argument(
        "--model",
        "-m",
        default=LLM_SETTINGS["default_model"],
        help="Model name to use for inference."
    )
    parser.add_argument(
        "--single-character",
        metavar="CHARACTER",
        help="Describe a single specific character."
    )
    parser.add_argument(
        "--wiki-url",
        metavar="URL",
        dest="wiki_url_template",
        help="Enable lookup on wiki using URL template (use {name} placeholder for character name)."
    )
    parser.add_argument(
        "--output-dir",
        metavar="DIR",
        dest="output_dir",
        default=str(OUTPUT_DIR),
        help="Directory to save output files (characters_descriptions.json and duplicate_replacement_map.json)."
    )
    args = parser.parse_args()

    client = get_llm_client(args.api_key, args.port)

    # Load characters from characters.json or extract from map files
    if os.path.exists(args.characters_file):
        characters = load_characters(args.characters_file)
        print(f"Loaded {len(characters)} characters from {args.characters_file}")
    else:
        # Try to extract characters from map files in the output_dir (chapters directory)
        chapters_path = Path(args.output_dir)
        if chapters_path.is_dir():
            characters = get_characters_from_map_files(chapters_path)
            print(f"Extracted {len(characters)} characters from map files in {args.output_dir}")
        else:
            print(f"Characters file not found: {args.characters_file}", file=sys.stderr)
            sys.exit(1)

    # Load chapter texts for context
    chapters_dir = Path(args.chapters_dir)
    chapter_texts = []
    chapter_files = []
    if chapters_dir.is_dir():
        chapter_files = sorted(chapters_dir.glob("chapter_*.txt"))
        for chapter_file in chapter_files:
            chapter_texts.append(load_chapter_text(str(chapter_file)))
        if args.verbose:
            print(f"Loaded {len(chapter_texts)} chapter files for context")

    # Describe characters
    if args.single_character:
        if args.single_character not in characters:
            print(f"Character '{args.single_character}' not found in characters list.", file=sys.stderr)
            sys.exit(1)
        if args.verbose:
            print(f"Describing single character: {args.single_character}")
        context_result = build_character_context(
            characters, chapter_texts, chapter_files,
            chapters_dir=Path(args.chapters_dir), wiki_url_template=args.wiki_url_template
        )
        context = context_result[0]
        chapter_messages = context_result[1] if len(context_result) > 1 else []
        description = describe_character(client, args.model, args.single_character, context, chapter_messages)
        print(f"\nDescription for '{args.single_character}':")
        print(description)
    else:
        # Use the public function for batch description
        descriptions = describe_characters(
            output_dir=args.output_dir,
            characters_file=args.characters_file,
            chapters_dir=args.chapters_dir,
            api_key=args.api_key,
            port=args.port,
            model=args.model,
            single_character=None,
            wiki_url_template=args.wiki_url_template,
            verbose=args.verbose
        )

        # Print summary
        print("\nCharacter descriptions generated:")
        for char, desc in descriptions.items():
            # Show first line of description
            first_line = desc.split('\n')[0][:80]
            # Handle Windows console encoding issues
            try:
                print(f"  - {char}: {first_line}...")
            except UnicodeEncodeError:
                # Fallback for Windows console
                safe_line = first_line.encode('utf-8', errors='replace').decode('utf-8')
                print(f"  - {char}: {safe_line}...")
# ============================================================================
# SHARED CHARACTER DESCRIPTION LOGIC
# ============================================================================

def describe_characters_shared(
    characters: list,
    chapter_texts: list,
    chapter_files: list,
    output_dir: str,
    client: OpenAI,
    model: str,
    wiki_url_template: str = "",
    verbose: bool = False,
    progress_callback: callable = None
) -> dict:
    """Shared logic for describing characters.

    Args:
        characters: List of character names
        chapter_texts: List of chapter text content
        chapter_files: List of chapter file paths
        output_dir: Directory to save output files
        client: OpenAI client instance
        model: Model name to use for inference
        wiki_url_template: Optional URL template for wiki lookup
        verbose: Print verbose output
        progress_callback: Optional callback(progress, desc) for progress updates

    Returns:
        Dict of character descriptions
    """
    # Step 1: De-dupe characters first
    duplicates = find_duplicate_characters(characters)
    if verbose and duplicates:
        print(f"Found duplicate character names: {duplicates}")

    # Create a map from duplicate names to canonical names
    duplicate_replacement_map = create_duplicate_replacement_map(duplicates)
    if verbose and duplicate_replacement_map:
        print(f"Duplicate replacement map: {duplicate_replacement_map}")

    # Get list of canonical characters (exclude duplicates)
    canonical_characters = [
        char for char in characters
        if char not in duplicate_replacement_map
    ]
    if verbose:
        print(f"Canonical characters to describe: {canonical_characters}")

    # Step 2: Loop over canonical characters
    descriptions = {}
    total_chars = len(canonical_characters)

    for idx, character in enumerate(canonical_characters, 1):
        if verbose:
            print(f"[{idx}/{total_chars}] Describing character: {character}")

        # Build context for this character using chapters_dir for dialogue extraction
        # Returns tuple of (context_string, chapter_messages_list)
        context_result = build_character_context(
            [character], chapter_texts, chapter_files,
            chapters_dir=Path(output_dir), wiki_url_template=wiki_url_template
        )
        context = context_result[0]
        chapter_messages = context_result[1] if len(context_result) > 1 else []

        # Call describe_character for this single character
        description = describe_character(client, model, character, context, chapter_messages)
        descriptions[character] = description

        # Save debug output for this character
        debug_output = {
            "model": model,
            "character": character,
            "system_prompt": CHARACTER_DESCRIPTION_PROMPT,
            "context": context,
            "description": description,
        }
        debug_file = os.path.join(
            output_dir, f"llm_character_debug_{character.replace(' ', '_')}.json"
        )
        with open(debug_file, "w", encoding="utf-8") as f:
            json.dump(debug_output, f, indent=2, ensure_ascii=False)
        if verbose:
            print(f"  Saved debug output to: {debug_file}")

        # Update progress
        progress = idx / total_chars if total_chars > 0 else 1.0
        if progress_callback:
            progress_callback(progress, f"Describing: {character}")
        if verbose:
            print(f"  Completed: {character}")

    deduped_descriptions = descriptions

    # Save duplicate replacement map to file
    replacement_map_file = os.path.join(output_dir, "duplicate_replacement_map.json")
    with open(replacement_map_file, 'w', encoding='utf-8') as f:
        json.dump(duplicate_replacement_map, f, indent=2, ensure_ascii=False)
    if verbose:
        print(f"Duplicate replacement map saved to: {replacement_map_file}")

    # Update characters.json with deduplicated list (canonical characters only)
    characters_file_path = os.path.join(output_dir, "characters.json")
    if os.path.exists(characters_file_path):
        with open(characters_file_path, 'r', encoding='utf-8') as f:
            original_data = json.load(f)
        # Update the characters list to only contain canonical names
        original_data['characters'] = canonical_characters
        with open(characters_file_path, 'w', encoding='utf-8') as f:
            json.dump(original_data, f, indent=2, ensure_ascii=False)
        if verbose:
            print(f"Updated characters.json with {len(canonical_characters)} canonical characters")

    # Save results (replacing em dashes with regular hyphens)
    output_file = os.path.join(output_dir, "characters_descriptions.json")
    with open(output_file, 'w', encoding='utf-8') as f:
        # Convert descriptions to JSON string and replace em dash with hyphen
        json_content = json.dumps(deduped_descriptions, indent=2, ensure_ascii=False)
        json_content = json_content.replace('\u2014', '-')
        f.write(json_content)
    if verbose:
        print(f"Character descriptions saved to: {output_file}")

    return deduped_descriptions


# ============================================================================
# PUBLIC FUNCTIONS - Module function for Gradio interface
# ============================================================================

from typing import Dict, Optional, Tuple, List


def describe_characters(
    output_dir: str,
    characters_file: str = "characters.json",
    chapters_dir: str = "chapters",
    api_key: str = None,
    port: str = None,
    model: str = "local-model",
    single_character: Optional[str] = None,
    wiki_url_template: str = "",
    verbose: bool = False,
    seed_characters: Dict[str, str] = None,
    progress_callback: callable = None
) -> Tuple[str, Dict[str, str]]:
    """Describe characters from an audiobook using an LLM.

    This is the main public function for character description. It can be called
    directly or used by the CLI. For backward compatibility with Gradio UI,
    this function handles all the orchestration.

    Args:
        output_dir: Directory to save output files
        characters_file: Path to characters.json file
        chapters_dir: Directory containing chapter text files
        api_key: API key for the LLM
        port: Port for the LLM inference
        model: Model name to use for inference
        single_character: Describe only one specific character
        wiki_url_template: Optional URL template for wiki lookup
        verbose: Print verbose output
        seed_characters: Dict mapping character names to voice paths from seed voices_map
        progress_callback: Optional callback(progress, desc) for progress updates

    Returns:
        Tuple of (status message, dict of character descriptions)
    """
    import json
    from pathlib import Path
    from openai import OpenAI

    chapters_path = Path(output_dir)

    # Load characters from characters.json or extract from map files
    if os.path.exists(characters_file):
        characters = load_characters(characters_file)
        if verbose:
            print(f"Loaded {len(characters)} characters from {characters_file}")
    else:
        # Try to extract characters from map files in the output_dir
        if chapters_path.is_dir():
            characters = get_characters_from_map_files(chapters_path)
            if verbose:
                print(f"Extracted {len(characters)} characters from map files in {output_dir}")
        else:
            if verbose:
                print(f"Characters file not found: {characters_file}", file=sys.stderr)
            return {}

    if not characters:
        if verbose:
            print("No characters found.", file=sys.stderr)
        return {}

    # Note: We do NOT filter out seed characters here. Seed characters will still be
    # described by the LLM (using their actual character names from the book), but
    # voice samples will not be generated for them (handled in generate_voice_samples).
    # This ensures that character descriptions are generated for all characters, not just
    # the ones without seed voices.

    if single_character:
        if single_character not in characters:
            if verbose:
                print(f"Character '{single_character}' not found.", file=sys.stderr)
            return {}
        characters = [single_character]

    # Load chapter texts for context (with caching)
    chapters_dir_path = Path(chapters_dir)
    if chapters_dir_path.is_dir():
        chapter_texts, chapter_files = load_chapter_texts_with_cache(chapters_dir_path)
        if verbose:
            print(f"Loaded {len(chapter_texts)} chapter files for context")
    else:
        chapter_texts, chapter_files = [], []

    # Initialize client
    client = get_llm_client(api_key or LLM_SETTINGS["api_key"], port or LLM_SETTINGS["port"])

    # Use shared logic
    descriptions = describe_characters_shared(
        characters=characters,
        chapter_texts=chapter_texts,
        chapter_files=chapter_files,
        output_dir=output_dir,
        client=client,
        model=model,
        wiki_url_template=wiki_url_template,
        verbose=verbose,
        progress_callback=progress_callback
    )

    result_msg = f"Successfully described {len(descriptions)} characters."
    return result_msg, descriptions


# Backward compatibility alias
describe_characters_in_dir = describe_characters