#!/usr/bin/env python3
"""
Module to describe characters from an audiobook using an LLM.
Reads characters from a characters.json file (generated by analyze_chapters.py)
and generates detailed descriptions for each character.
"""
import glob
import json
import os
import re
import sys
import threading
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path
from typing import Dict, List, Optional, Tuple
from openai import OpenAI

from .config import LLM_SETTINGS, OUTPUT_DIR
from .utils import get_llm_client, compare_characters, get_characters_from_map_files, natural_sort_key


# Default prompt for character description (OmniVoice format)
CHARACTER_DESCRIPTION_PROMPT_OMNI = """You are an expert voice actor. Create VERY SHORT voice profiles optimized for TTS (text-to-speech) synthesis.

CRITICAL: Output MUST be in OmniVoice format - comma-separated attributes only.

OMNIVOICE SUPPORTED ATTRIBUTES:
- Gender: male, female
- Age: child, teenager, young adult, middle-aged, elderly
- Pitch: very low pitch, low pitch, moderate pitch, high pitch, very high pitch
- Style: whisper
- English Accents: american accent, british accent, australian accent, canadian accent, indian accent, chinese accent, korean accent, japanese accent, portuguese accent, russian accent

CRITICAL RULES:
- Output ONLY comma-separated attributes (no other text)
- NO markdown, NO sentences, NO "a", NO "with", NO "voice"
- Use ONLY the supported attributes listed above
- 2-5 attributes max, comma-separated
- ONE gender only (male OR female, NOT both)
- ONE age only (child OR teenager OR young adult OR middle-aged OR elderly)
- ONE pitch only
- ONE accent only (or omit if not applicable)
- NEVER combine multiple genders, ages, or pitches in one description

Format: <gender>, <age>, <pitch>, <accent>

Good Examples (OmniVoice format):
- male, middle-aged, moderate pitch
- female, young adult, high pitch, british accent
- male, elderly, low pitch
- female, young adult, moderate pitch, american accent
- male, middle-aged, high pitch

BAD Examples (do NOT use):
- A middle-aged male with a smooth voice.
- male. middle aged. high
- An elderly male with a gravelly voice.
- male, female, young adult (conflicting genders)
- male, young adult, middle-aged, elderly (multiple ages)
- male, middle-aged, high pitch, low pitch (conflicting pitches)

For group characters like "crowd", "voices", or "people", pick ONE representative voice (e.g., "male, middle-aged, moderate pitch").
"""

# VoxCPM format prompt
CHARACTER_DESCRIPTION_PROMPT_VOX = """You are an expert voice actor. Create rich, detailed voice profiles for VoxCPM TTS synthesis.

CRITICAL: Output MUST be in natural language format, wrapped in parentheses.

VOXCPM FORMATTING:
- Start with "(" and end with ")"
- Combine multiple ingredients into ONE comprehensive description
- Support both English and Chinese

THREE INGREDIENTS TO MIX:

1. BASIC (The Base) - Core identity: gender, age, role
   Examples: middle-aged male broadcaster, elderly woman, young female narrator

2. TEXTURED (The Marinade) - Voice quality and pitch
   Examples: low-pitched, raspy, magnetic, gravelly, smooth, breathy, warm

3. VIVID (The Presentation) - Emotion, pacing, scenario
   Examples: passionate, shouting, gentle, slow tone, energetic, calm narration

COMBINE ALL THREE into a single rich description like a signature recipe.

Good Examples (VoxCPM format):
- (middle-aged male broadcaster, low-pitched and magnetic voice, passionate delivery with rhythmic pacing)
- (elderly woman, raspy and grainy texture with subtle breathy tremors, slow gentle tone perfect for historical narration)
- (young female narrator, warm and smooth voice, energetic and engaging with clear articulation)
- (deep-voiced male villain, gravelly and menacing texture, slow deliberate pacing with dark undertones)
- (cheerful child, high-pitched and bright, excited and rapid speech pattern)

BAD Examples (do NOT use):
- male, middle-aged, high pitch (too brief, missing emotional/presentation layer)
- A middle-aged male with a smooth voice. (not wrapped in parentheses, too simple)
- male, female, young adult (conflicting attributes)
- (male, old) (only basic ingredient, missing texture and vividness)
"""

# Universal JSON format prompt - structured output that any engine can parse
CHARACTER_DESCRIPTION_PROMPT_UNIVERSAL = """Output ONLY a JSON object. No prose, no explanation, no markdown.

Format:
{{
  "gender": "male" or "female",
  "age": "child" or "teenager" or "young adult" or "middle-aged" or "elderly",
  "pitch": "very low" or "low" or "moderate" or "high" or "very high",
  "accent": "american" or "british" or "australian" or "canadian" or "indian" or "chinese" or "korean" or "japanese" or "portuguese" or "russian" or omit,
  "style": 1-3 traits from: raspy, gravelly, smooth, breathy, nasal, booming, whispery, hoarse, metallic, guttural, warm, cold, aristocratic, streetwise, scholarly, rural, nervous, calm, cheerful, dark, bright, gentle, sharp, rough, clear, mellow, authoritative, anxious, cheerful, deep, soft, gentle, sharp, rough, clear, mellow, authoritative, anxious, cheerful, deep, soft,
  "description": 2-4 sentence paragraph describing how this character speaks vividly,
  "celebrity_voice": Full name of a celebrity whose voice matches this character (e.g., "Benedict Cumberbatch", "Morgan Freeman", "Scarlett Johansson"). Choose living or recently-deceased celebrities with plenty of audio available. Pick someone whose natural speaking voice matches the character's voice description.
}}

RULES:
- ONE gender, ONE age, ONE pitch, ONE accent (or omit), 1-3 style traits
- "description" MUST be natural language
- "celebrity_voice" MUST be a real celebrity name (NOT fictional characters)
- MAKE SIMILAR CHARACTERS DISTINCT: Different pitch and style for characters with same gender/age
- Your entire response is the JSON object. Nothing else.

Examples:
{{"gender": "male", "age": "middle-aged", "pitch": "moderate", "style": "smooth, aristocratic", "description": "A smooth middle-aged aristocrat with a calm, measured cadence. He carries himself with quiet authority and speaks with the polished ease of someone accustomed to high society. His tone is warm but restrained.", "celebrity_voice": "Benedict Cumberbatch"}}
{{"gender": "female", "age": "young adult", "pitch": "high", "accent": "british", "style": "breathy, warm", "description": "A warm young woman with a breathy, inviting voice. She speaks with genuine kindness and a touch of British refinement. Her tone is cheerful and open, suggesting a nurturing personality.", "celebrity_voice": "Emma Watson"}}
{{"gender": "male", "age": "elderly", "pitch": "very low", "style": "gravelly, raspy", "description": "A gravelly old man whose voice carries the weight of age and hardship. He speaks slowly and deliberately, each word measured. His tone is rough but not unkind.", "celebrity_voice": "Morgan Freeman"}}
{{"gender": "female", "age": "young adult", "pitch": "moderate", "accent": "american", "description": "A cheerful young woman with a bright, energetic voice. She speaks with enthusiasm and an American accent, her tone suggesting confidence and warmth.", "celebrity_voice": "Jennifer Lawrence"}}
{{"gender": "male", "age": "young adult", "pitch": "high", "style": "thin, nervous", "description": "A nervous young man with a thin, anxious voice. He speaks quickly and with uncertainty, his tone betraying insecurity and a lack of confidence.", "celebrity_voice": "Tom Holland"}}

For group characters like "crowd", "voices", or "people", pick ONE representative voice.
"""


def load_characters(characters_file: str) -> List[str]:
    """Load characters from a JSON file."""
    with open(characters_file, 'r', encoding='utf-8') as f:
        data = json.load(f)
    return data.get('characters', [])


def find_duplicate_characters(characters: List[str]) -> Dict[str, List[str]]:
    """Find groups of duplicate characters based on name similarity.

    Returns a dict mapping canonical character name to list of duplicate names.
    """
    canonical_to_duplicates: dict = {}

    for char in characters:
        if char == "narrator":
            continue

        found_canonical = None
        for canonical in canonical_to_duplicates.keys():
            if compare_characters(char, canonical):
                found_canonical = canonical
                break

        if found_canonical:
            canonical_to_duplicates[canonical].append(char)
        else:
            canonical_to_duplicates[char] = []

    # Filter out entries with no duplicates
    return {k: v for k, v in canonical_to_duplicates.items() if v}


def create_duplicate_replacement_map(duplicates: Dict[str, List[str]]) -> Dict[str, str]:
    """Create a mapping from each duplicate name to its canonical name.

    Args:
        duplicates: Dict mapping canonical name to list of duplicate names

    Returns:
        Dict mapping duplicate character names to their canonical name
    """
    replacement_map = {}
    for canonical, duplicates_list in duplicates.items():
        for dup_name in duplicates_list:
            replacement_map[dup_name] = canonical
    return replacement_map


def deduplicate_descriptions(descriptions: Dict[str, str], duplicates: Dict[str, List[str]], verbose: bool = False) -> Dict[str, str]:
    """Deduplicate character descriptions based on duplicate character mappings.

    For each group of duplicate characters:
    - Keep the canonical character's description
    - Add "See <canonical> (same character)." for duplicates

    Args:
        descriptions: Dict mapping character names to their descriptions
        duplicates: Dict mapping canonical name to list of duplicate names
        verbose: Enable verbose output

    Returns:
        Dict with duplicates replaced by references to canonical characters
    """
    deduped = descriptions.copy()

    for canonical, duplicates_list in duplicates.items():
        # Add references for duplicates
        for dup_name in duplicates_list:
            if dup_name in descriptions:
                if verbose:
                    print(f"Marking '{dup_name}' as duplicate of '{canonical}'")
                deduped[dup_name] = f"See {canonical} (same character)."
            else:
                if verbose:
                    print(f"Duplicate '{dup_name}' not found in descriptions")

    return deduped


def load_chapter_text(chapter_file: str) -> str:
    """Load text from a chapter file."""
    with open(chapter_file, 'r', encoding='utf-8') as f:
        return f.read()


def load_chapter_texts(chapters_dir: Path) -> Tuple[List[str], List[Path]]:
    """Load chapter texts from a directory.

    Args:
        chapters_dir: Path to the chapters directory

    Returns:
        Tuple of (list of chapter texts, list of chapter file paths)
    """
    chapter_files = sorted(chapters_dir.glob("chapter_*.txt"), key=natural_sort_key)
    chapter_texts = [load_chapter_text(str(f)) for f in chapter_files]
    return chapter_texts, chapter_files


def find_chapters_with_character(chapter_texts: List[str], chapter_files: List[Path], character_name: str) -> List[Tuple[Path, str]]:
    """Find chapters where a character is mentioned.

    Args:
        chapter_texts: List of chapter text content
        chapter_files: List of chapter file paths (in matching order)
        character_name: The character name to search for

    Returns:
        List of (chapter_file, chapter_text) tuples where character appears
    """
    chapters_with_char = []
    char_lower = character_name.lower()

    for text, filepath in zip(chapter_texts, chapter_files):
        if char_lower in text.lower():
            chapters_with_char.append((filepath, text))

    return chapters_with_char


def load_chapter_lines(chapter_file: str) -> List[str]:
    """Load a chapter file and return lines as a list (1-indexed for convenience).

    Args:
        chapter_file: Path to the chapter text file

    Returns:
        List of lines with empty string at index 0 for 1-indexed access
        (Line N: prefixes are stripped if present)
    """
    with open(chapter_file, 'r', encoding='utf-8') as f:
        lines = f.readlines()
    # Remove trailing newlines, strip "Line N: " prefix if present, and make 1-indexed
    cleaned_lines = ['']  # Empty string at index 0 for 1-indexed access
    for line in lines:
        line = line.rstrip('\n\r')
        # Strip "Line N: " prefix if present
        if line.startswith("Line"):
            match = re.match(r'^Line\s+\d+:\s*(.*)$', line)
            if match:
                line = match.group(1)
        cleaned_lines.append(line)
    return cleaned_lines


def extract_character_dialogue(chapters_dir: Path, character_name: str, max_examples: Optional[int] = None) -> List[Tuple[str, str]]:
    """Extract actual dialogue lines spoken by a character from map files.

    Args:
        chapters_dir: Path to the chapters directory
        character_name: The character name to extract dialogue for
        max_examples: Maximum number of dialogue examples to return (None = all lines)

    Returns:
        List of (chapter_name, dialogue_line) tuples
    """
    dialogue_examples = []
    char_lower = character_name.lower()

    # Get all map files sorted
    map_files = sorted([f for f in chapters_dir.glob("*.map.json")
                       if re.match(r"^chapter_\d+\.map\.json$", f.name)],
                      key=natural_sort_key)

    for map_file in map_files:
        try:
            with open(map_file, "r", encoding="utf-8") as f:
                data = json.load(f)

            # Handle both list format [char_map, line_map] and dict format
            if isinstance(data, list) and len(data) >= 2:
                character_map = data[0]
                line_map = data[1]
            elif isinstance(data, dict):
                character_map = data.get("character_map", {})
                line_map = data.get("line_map", {})
            else:
                continue

            # Find the speaker key for this character
            character_speaker_key = None
            for speaker_key, char_name in character_map.items():
                if char_name.lower() == char_lower:
                    character_speaker_key = speaker_key
                    break

            if character_speaker_key is None:
                continue

            # Find all lines attributed to this character's speaker key
            character_lines = []
            for line_num_str, speaker_key_in_line in line_map.items():
                if str(speaker_key_in_line) == str(character_speaker_key):
                    character_lines.append(int(line_num_str))

            # Load chapter text and extract dialogue
            # Map files are named chapter_N.map.json, text files are chapter_N.txt
            # So we need to strip the ".map" suffix from the stem
            map_stem = map_file.stem  # e.g., "chapter_0.map"
            chapter_stem = map_stem.rsplit(".map", 1)[0]  # e.g., "chapter_0"
            chapter_txt_file = chapter_stem + ".txt"
            chapter_txt_path = chapters_dir / chapter_txt_file
            if chapter_txt_path.exists():
                lines = load_chapter_lines(str(chapter_txt_path))
                for line_num in sorted(character_lines):
                    if line_num < len(lines):
                        line_text = lines[line_num]
                        # Only include lines that look like dialogue (start with quote)
                        if line_text.strip().startswith('"'):
                            dialogue_examples.append((map_file.stem, line_text.strip()))
                            if max_examples is not None and len(dialogue_examples) >= max_examples:
                                break
        except Exception:
            continue

    return dialogue_examples


def build_character_context(characters: List[str], chapter_texts: List[str], chapter_files: List[Path] = [],
                            chapters_dir: Optional[Path] = None, wiki_url_template: str = "",
                            all_characters: Optional[List[str]] = None) -> Tuple[str, List[str]]:
    """Build context string with character names and their actual dialogue.

    Args:
        characters: List of character names
        chapter_texts: List of chapter text content (deprecated, kept for compatibility)
        chapter_files: List of chapter file paths (deprecated, kept for compatibility)
        chapters_dir: Path to chapters directory (preferred method)
        wiki_url_template: Optional URL template for wiki lookup (with {name} placeholder)
        all_characters: Optional list of ALL characters being described (for differentiation)

    Returns:
        Tuple of (context string, list of chapter-based dialogue messages)
    """
    context = "Characters to describe:\n"
    for char in characters:
        context += f"{char}\n"

    if all_characters and len(all_characters) > 1:
        context += "\nOther characters in the book (make this character's voice distinct from these):\n"
        for char in all_characters:
            if char not in characters:
                context += f"{char}\n"

    # Build character-specific context using actual dialogue from map files
    context = "Character dialogue examples from the book:\n"
    chapter_messages = []

    if chapters_dir and chapters_dir.is_dir():
        for char in characters:
            if char == "narrator":
                # Narrator has no dialogue - use brief chapter text excerpts for context
                context += f"\n--- {char} ---\n(The narrator provides the narration for this book)\n"
                chapter_messages.append("The narrator provides the narration for this book. Here are a few narration excerpts:\n")
                for f in sorted(chapters_dir.glob("chapter_*.txt"))[:2]:
                    lines = f.read_text().split("\n")
                    narration = [l for l in lines if not l.strip().startswith('"')]
                    # Only take first 3 lines per chapter to keep context small
                    chapter_messages.append(f"From {f.name}:\n" + "\n".join(narration[:3]))
                continue
            dialogue_examples = extract_character_dialogue(chapters_dir, char, max_examples=None)
            if dialogue_examples:
                context += f"\n--- {char} ---\n"
                chapter_messages.append(f"Here is all the dialogue spoken by {char} from each chapter:\n")
                for chapter_name, dialogue_line in dialogue_examples:
                    context += f"{dialogue_line}\n"
                    chapter_messages.append(f"From {chapter_name}:\n{dialogue_line}")
            else:
                context += f"\n--- {char} ---\n(No direct dialogue found)\n"
    elif chapter_files and len(chapter_files) == len(chapter_texts):
        # Fallback to old method if chapters_dir not provided
        for char in characters:
            relevant_chapters = find_chapters_with_character(chapter_texts, chapter_files, char)
            if relevant_chapters:
                # context += f"\n--- {char} Context ---\n"
                for filepath, text in relevant_chapters[:2]:
                    # context += f"[From {filepath.name}]\n"
                    context += text[:800] + "\n"
    else:
        # Fallback to first 3 chapters for all characters
        for i, text in enumerate(chapter_texts[:3]):
            context += f"--- Chapter {i+1} Excerpt ---\n"
            context += text[:1000] + "\n\n"

    return context, chapter_messages


def _get_description_prompt(voice_engine: Optional[str]) -> str:
    """Get the character description prompt. All engines use universal JSON format."""
    return CHARACTER_DESCRIPTION_PROMPT_UNIVERSAL


def _parse_universal_description(raw: str) -> Optional[Dict[str, str]]:
    """Parse and validate a universal JSON description.

    Handles JSON embedded in prose, markdown code blocks, or plain JSON.
    Falls back to extracting values from prose if no JSON found.
    Returns dict with keys 'gender', 'age', 'pitch', 'accent', 'style', 'celebrity_voice' or None if invalid.
    """
    try:
        text = raw.strip()
        # Try direct parse first
        try:
            obj = json.loads(text)
        except json.JSONDecodeError:
            # Try extracting JSON from markdown code block
            if "```" in text:
                text = text.split("\n", 1)[1] if "\n" in text else text
                if text.endswith("```"):
                    text = text[:-3]
            # Try finding JSON object anywhere in the text
            start = text.find("{")
            end = text.rfind("}") + 1
            if start >= 0 and end > start:
                text = text[start:end]
            try:
                obj = json.loads(text)
            except json.JSONDecodeError:
                # Fallback: extract values from prose
                return _extract_from_prose(raw)
        gender = obj.get("gender", "").lower()
        age = obj.get("age", "").lower()
        pitch = obj.get("pitch", "moderate").lower()
        accent = obj.get("accent", "").lower()
        style = obj.get("style", "")
        celebrity_voice = obj.get("celebrity_voice", "")
        if gender not in ("male", "female"):
            return None
        if age not in ("child", "teenager", "young adult", "middle-aged", "elderly", "young", "middle-aged", "old"):
            return None
        return {"gender": gender, "age": age, "pitch": pitch, "accent": accent, "style": style, "celebrity_voice": celebrity_voice}
    except (json.JSONDecodeError, AttributeError):
        return None


def _extract_from_prose(text: str) -> Optional[Dict[str, str]]:
    """Extract gender, age, pitch from prose output as fallback."""
    import re
    text_lower = text.lower()

    # Extract gender
    gender = None
    if "male" in text_lower or "man" in text_lower or "boy" in text_lower:
        gender = "male"
    elif "female" in text_lower or "woman" in text_lower or "girl" in text_lower:
        gender = "female"
    if not gender:
        return None

    # Extract age
    age = None
    age_patterns = [
        (r"\byoung\b", "young adult"),
        (r"\bchild\b", "child"),
        (r"\bteen\b", "teenager"),
        (r"\bteenager\b", "teenager"),
        (r"\bmiddle-aged\b", "middle-aged"),
        (r"\bmiddle aged\b", "middle-aged"),
        (r"\bold\b", "elderly"),
        (r"\belderly\b", "elderly"),
        (r"\bsenior\b", "elderly"),
    ]
    for pattern, val in age_patterns:
        if re.search(pattern, text_lower):
            age = val
            break
    if not age:
        age = "middle-aged"  # default

    # Extract pitch
    pitch = None
    pitch_patterns = [
        (r"\bvery low\b", "very low"),
        (r"\blow pitch\b", "low"),
        (r"\blow\b", "low"),
        (r"\bmoderate\b", "moderate"),
        (r"\bmedium\b", "moderate"),
        (r"\bhigh pitch\b", "high"),
        (r"\bhigh\b", "high"),
        (r"\bvery high\b", "very high"),
    ]
    for pattern, val in pitch_patterns:
        if re.search(pattern, text_lower):
            pitch = val
            break
    if not pitch:
        pitch = "moderate"  # default

    # Extract accent
    accent = None
    accent_patterns = [
        (r"\bamerican\b", "american"),
        (r"\bbritish\b", "british"),
        (r"\benglish\b", "british"),
        (r"\baustralian\b", "australian"),
        (r"\bcanadian\b", "canadian"),
        (r"\bindian\b", "indian"),
    ]
    for pattern, val in accent_patterns:
        if re.search(pattern, text_lower):
            accent = val
            break

    # Extract style traits
    style_words = []
    style_candidates = [
        "raspy", "gravelly", "smooth", "breathy", "nasal", "booming",
        "whispery", "hoarse", "metallic", "guttural", "warm", "cold",
        "aristocratic", "streetwise", "scholarly", "rural", "deep",
        "soft", "gentle", "sharp", "rough", "clear", "mellow",
        "authoritative", "nervous", "anxious", "calm", "cheerful",
        "dark", "light", "bright", "dark", "warm", "cold",
    ]
    for word in style_candidates:
        if word in text_lower:
            style_words.append(word)
    style = ", ".join(style_words[:3]) if style_words else ""

    # Build description from the prose itself (use first 4 sentences)
    sentences = re.split(r'[.!?]+', text.replace('\n', ' '))
    sentences = [s.strip() for s in sentences if len(s.strip()) > 20]
    description = ". ".join(sentences[:4]) if sentences else text[:200]

    return {
        "gender": gender,
        "age": age,
        "pitch": pitch,
        "accent": accent or "",
        "style": style,
        "description": description,
        "celebrity_voice": "",
    }


def _universal_description_to_omni(parsed: Dict[str, str]) -> str:
    """Convert universal JSON description to OmniVoice comma-separated format."""
    parts = [parsed["gender"], parsed["age"]]
    pitch_map = {"very low": "very low pitch", "low": "low pitch", "moderate": "moderate pitch", "high": "high pitch", "very high": "very high pitch"}
    pitch = pitch_map.get(parsed.get("pitch", "moderate"), "moderate pitch")
    parts.append(pitch)
    if parsed.get("accent"):
        accent_map = {"american": "american accent", "british": "british accent", "australian": "australian accent", "canadian": "canadian accent", "indian": "indian accent", "chinese": "chinese accent", "korean": "korean accent", "japanese": "japanese accent", "portuguese": "portuguese accent", "russian": "russian accent"}
        accent = accent_map.get(parsed["accent"], parsed["accent"])
        parts.append(accent)
    return ", ".join(parts)


def _universal_description_to_dramabox(parsed: Dict[str, str]) -> str:
    """Convert universal JSON description to Dramabox prompt format."""
    parts = [parsed["gender"], parsed["age"]]
    if parsed.get("pitch"):
        parts.append(parsed["pitch"])
    if parsed.get("accent"):
        parts.append(parsed["accent"])
    if parsed.get("style"):
        parts.extend(s.strip() for s in parsed["style"].split(","))
    return ", ".join(parts)


def _universal_description_to_vox(parsed: Dict[str, str]) -> str:
    """Convert universal JSON description to VoxCPM format."""
    parts = [parsed["gender"], parsed["age"]]
    if parsed.get("pitch"):
        parts.append(parsed["pitch"])
    if parsed.get("style"):
        parts.extend(s.strip() for s in parsed["style"].split(","))
    if parsed.get("accent"):
        parts.append(parsed["accent"])
    return f"({', '.join(parts)})"


def describe_character(client: OpenAI, model: str, character: str, context: str, chapter_messages: Optional[List[str]] = None, voice_engine: Optional[str] = None, max_retries: int = 3, used_celebrities: Optional[List[str]] = None) -> str:
    """Ask the LLM to describe a single character.

    Returns the raw JSON string. Engine adapters convert to their format.

    Args:
        client: OpenAI client instance
        model: Model name to use for inference
        character: Character name to describe
        context: Character description context string
        chapter_messages: Optional list of chapter-based dialogue messages
        voice_engine: TTS engine (unused - all engines use same JSON format)
        max_retries: Max retries for failed LLM calls
        used_celebrities: List of celebrity names already assigned to other characters

    Returns:
        Raw JSON string describing the character.
    """
    system_prompt = _get_description_prompt(voice_engine)

    # Add used celebrities constraint to system prompt
    if used_celebrities:
        system_prompt += f"\n\nIMPORTANT: Do NOT use these celebrities (they are already assigned to other characters): {', '.join(used_celebrities)}\nPick a DIFFERENT celebrity for this character."

    # System prompt first
    messages = [
        {"role": "system", "content": system_prompt},
    ]

    # Add chapter messages as separate user messages if provided
    if chapter_messages:
        for chapter_msg in chapter_messages:
            messages.append({"role": "user", "content": chapter_msg})

    # Final user message with the character to describe and summary context
    messages.append({"role": "user", "content": f"Describe this character: {character} \n\nContext:\n{context}"})

    for attempt in range(max_retries):
        try:
            response = client.chat.completions.create(
                model=model,
                messages=messages,
            )
            raw = response.choices[0].message.content
            # Validate universal JSON format
            parsed = _parse_universal_description(raw)
            if parsed:
                # If we got prose, convert parsed result to JSON for storage
                if "description" in parsed:
                    # Prose fallback — return as JSON
                    return json.dumps(parsed)
                return raw  # Return raw JSON for storage
            # Retry with feedback
            messages.append({"role": "assistant", "content": raw})
            messages.append({"role": "user", "content": "Invalid output. Gender must be 'male' or 'female', age must be 'child', 'teenager', 'young adult', 'middle-aged', or 'elderly'. Return valid JSON."})
        except Exception as e:
            if attempt == max_retries - 1:
                return f"Error describing character: {e}"
    return f"Error: Failed to generate valid description for {character} after {max_retries} attempts"


def describe_all_characters(client: OpenAI, model: str, characters: List[str], context: str, voice_engine: Optional[str] = None) -> Dict[str, str]:
    """Ask the LLM to describe all characters at once."""
    system_prompt = _get_description_prompt(voice_engine)

    # Build the user message
    user_message = f"Describe all these characters in detail. Return a JSON object with character names as keys and descriptions as values.\n\nCharacters:\n{chr(10).join(characters)}\n\nContext:\n{context}"

    messages = [
        {"role": "system", "content": system_prompt},
        {"role": "user", "content": user_message}
    ]

    try:
        response = client.chat.completions.create(
            model=model,
            messages=messages
        )
        content = response.choices[0].message.content
        # Try to parse JSON from response
        try:
            # Remove markdown code blocks if present
            if content.startswith('```json'):
                content = content[7:]
            if content.startswith('```'):
                content = content[3:]
            if content.endswith('```'):
                content = content[:-3]
            content = content.strip()
            parsed = json.loads(content)

            # Validate that the response contains all expected character names
            # Check for at least one matching character name (case-insensitive)
            missing_chars = []
            for char in characters:
                char_lower = char.lower()
                found = any(k.lower() == char_lower for k in parsed.keys())
                if not found:
                    missing_chars.append(char)

            if missing_chars:
                # If we're missing character names, the LLM likely returned the example names
                # Instead of the actual character names - use fallback
                print(f"Warning: LLM response missing character names: {missing_chars}. Using fallback.")
                return {char: content for char in characters}

            return parsed
        except json.JSONDecodeError:
            # If parsing fails, return raw content
            return {char: content for char in characters}
    except Exception as e:
        print(f"Error describing characters: {e}", file=sys.stderr)
        return {}
# ============================================================================
# SHARED CHARACTER DESCRIPTION LOGIC
# ============================================================================

def describe_characters_shared(
    characters: List[str],
    chapter_texts: List[str],
    chapter_files: List[Path],
    output_dir: str,
    client: OpenAI,
    model: str,
    wiki_url_template: str = "",
    verbose: bool = False,
    progress_callback: Optional[callable] = None,
    voice_engine: Optional[str] = None,
    max_concurrent: int = 1
) -> Dict[str, str]:
    """Shared logic for describing characters.

    Args:
        characters: List of character names
        chapter_texts: List of chapter text content
        chapter_files: List of chapter file paths
        output_dir: Directory to save output files
        client: OpenAI client instance
        model: Model name to use for inference
        wiki_url_template: Optional URL template for wiki lookup
        verbose: Print verbose output
        progress_callback: Optional callback for progress updates
        voice_engine: TTS engine for voice generation ('omni', 'vox', etc.)
        max_concurrent: Maximum number of concurrent LLM calls (default 1, set higher to parallelize)

    Returns:
        Dict of character descriptions
    """
    # Step 1: De-dupe characters first
    duplicates = find_duplicate_characters(characters)
    if verbose and duplicates:
        print(f"Found duplicate character names: {duplicates}")

    # Create a map from duplicate names to canonical names
    duplicate_replacement_map = create_duplicate_replacement_map(duplicates)
    if verbose and duplicate_replacement_map:
        print(f"Duplicate replacement map: {duplicate_replacement_map}")

    # Get list of canonical characters (exclude duplicates)
    canonical_characters = [
        char for char in characters
        if char not in duplicate_replacement_map
    ]
    if verbose:
        print(f"Canonical characters to describe: {canonical_characters}")

    # Step 2: Loop over canonical characters (parallel if max_concurrent > 1)
    descriptions = {}
    total_chars = len(canonical_characters)

    # Thread-safe set to track used celebrities across parallel workers
    used_celebrities_lock = threading.Lock()
    used_celebrities: set = set()

    if max_concurrent > 1 and total_chars > 1:
        if verbose:
            print(f"Describing {total_chars} characters with {max_concurrent} concurrent workers...")

        def _describe_one(character: str, idx: int) -> Tuple[str, str, str]:
            if verbose:
                print(f"[{idx}/{total_chars}] Describing character: {character}")

            context_result = build_character_context(
                [character], chapter_texts, chapter_files,
                chapters_dir=Path(output_dir), wiki_url_template=wiki_url_template,
                all_characters=canonical_characters
            )
            context = context_result[0]
            chapter_messages = context_result[1] if len(context_result) > 1 else []

            # Get current list of used celebrities (thread-safe read)
            with used_celebrities_lock:
                current_used = list(used_celebrities)

            description = describe_character(client, model, character, context, chapter_messages, voice_engine=voice_engine, used_celebrities=current_used)

            # Extract celebrity from description and add to used set (thread-safe write)
            try:
                desc_obj = json.loads(description) if isinstance(description, str) else description
                if isinstance(desc_obj, dict):
                    celeb = desc_obj.get("celebrity_voice", "")
                    if celeb:
                        with used_celebrities_lock:
                            used_celebrities.add(celeb)
                            if verbose:
                                print(f"  [CELEB-DEDUP] Assigned '{celeb}' to '{character}' (now {len(used_celebrities)} unique celebrities)")
            except (json.JSONDecodeError, AttributeError):
                pass

            debug_output = {
                "model": model,
                "character": character,
                "system_prompt": _get_description_prompt(voice_engine),
                "context": context,
                "description": description,
            }
            debug_file = os.path.join(
                output_dir, f"llm_character_debug_{character.replace(' ', '_')}.json"
            )
            with open(debug_file, "w", encoding="utf-8") as f:
                json.dump(debug_output, f, indent=2, ensure_ascii=False)
            if verbose:
                print(f"  Saved debug output to: {debug_file}")

            return (character, description, f"  Completed: {character}")

        with ThreadPoolExecutor(max_workers=max_concurrent) as executor:
            futures = {executor.submit(_describe_one, char, i + 1): i + 1 for i, char in enumerate(canonical_characters)}
            completed = 0
            for future in as_completed(futures):
                completed += 1
                character, desc, msg = future.result()
                descriptions[character] = desc
                if verbose:
                    print(msg)
                if progress_callback:
                    progress_callback(completed / total_chars, f"Describing: {character}")
    else:
        for idx, character in enumerate(canonical_characters, 1):
            if verbose:
                print(f"[{idx}/{total_chars}] Describing character: {character}")

            context_result = build_character_context(
                [character], chapter_texts, chapter_files,
                chapters_dir=Path(output_dir), wiki_url_template=wiki_url_template,
                all_characters=canonical_characters
            )
            context = context_result[0]
            chapter_messages = context_result[1] if len(context_result) > 1 else []

            description = describe_character(client, model, character, context, chapter_messages, voice_engine=voice_engine, used_celebrities=list(used_celebrities))
            descriptions[character] = description

            # Extract celebrity and add to used set
            try:
                desc_obj = json.loads(description) if isinstance(description, str) else description
                if isinstance(desc_obj, dict):
                    celeb = desc_obj.get("celebrity_voice", "")
                    if celeb:
                        used_celebrities.add(celeb)
                        if verbose:
                            print(f"  [CELEB-DEDUP] Assigned '{celeb}' to '{character}' (now {len(used_celebrities)} unique celebrities)")
            except (json.JSONDecodeError, AttributeError):
                pass

            debug_output = {
                "model": model,
                "character": character,
                "system_prompt": _get_description_prompt(voice_engine),
                "context": context,
                "description": description,
            }
            debug_file = os.path.join(
                output_dir, f"llm_character_debug_{character.replace(' ', '_')}.json"
            )
            with open(debug_file, "w", encoding="utf-8") as f:
                json.dump(debug_output, f, indent=2, ensure_ascii=False)
            if verbose:
                print(f"  Saved debug output to: {debug_file}")

            progress = idx / total_chars if total_chars > 0 else 1.0
            if progress_callback:
                progress_callback(progress, f"Describing: {character}")
            if verbose:
                print(f"  Completed: {character}")

    deduped_descriptions = descriptions

    # Save duplicate replacement map to file
    replacement_map_file = os.path.join(output_dir, "duplicate_replacement_map.json")
    with open(replacement_map_file, 'w', encoding='utf-8') as f:
        json.dump(duplicate_replacement_map, f, indent=2, ensure_ascii=False)
    if verbose:
        print(f"Duplicate replacement map saved to: {replacement_map_file}")

    # Update characters.json with deduplicated list (canonical characters only)
    characters_file_path = os.path.join(output_dir, "characters.json")
    if os.path.exists(characters_file_path):
        with open(characters_file_path, 'r', encoding='utf-8') as f:
            original_data = json.load(f)
        # Update the characters list to only contain canonical names
        original_data['characters'] = canonical_characters
        with open(characters_file_path, 'w', encoding='utf-8') as f:
            json.dump(original_data, f, indent=2, ensure_ascii=False)
        if verbose:
            print(f"Updated characters.json with {len(canonical_characters)} canonical characters")

    # Save results (replacing em dashes with regular hyphens)
    output_file = os.path.join(output_dir, "characters_descriptions.json")
    with open(output_file, 'w', encoding='utf-8') as f:
        # Convert descriptions to JSON string and replace em dash with hyphen
        json_content = json.dumps(deduped_descriptions, indent=2, ensure_ascii=False)
        json_content = json_content.replace('\u2014', '-')
        f.write(json_content)
    if verbose:
        print(f"Character descriptions saved to: {output_file}")

    return deduped_descriptions


# ============================================================================
# PUBLIC FUNCTIONS - Module function for Gradio interface
# ============================================================================

from typing import Dict, Optional, Tuple, List


def describe_characters(
    output_dir: str,
    characters_file: str = "characters.json",
    chapters_dir: str = "chapters",
    api_key: str = None,
    port: str = None,
    model: str = None,
    single_character: Optional[str] = None,
    wiki_url_template: str = "",
    verbose: bool = False,
    seed_characters: Dict[str, str] = None,
    progress_callback: callable = None,
    voice_engine: str = None,
    client: "OpenAI" = None,
    max_concurrent: int = 1
) -> Tuple[str, Dict[str, str]]:
    """Describe characters from an audiobook using an LLM.

    This is the main public function for character description. It can be called
    directly or used by the CLI. For backward compatibility with Gradio UI,
    this function handles all the orchestration.

    Args:
        output_dir: Directory to save output files
        characters_file: Path to characters.json file
        chapters_dir: Directory containing chapter text files
        api_key: API key for the LLM
        port: Port for the LLM inference
        model: Model name to use for inference
        single_character: Describe only one specific character
        wiki_url_template: Optional URL template for wiki lookup
        verbose: Print verbose output
        seed_characters: Dict mapping character names to voice paths from seed voices_map
        progress_callback: Optional callback(progress, desc) for progress updates
        voice_engine: TTS engine for voice generation ('omni', 'vox', etc.) - affects prompt format
        client: Optional LLM client for injection (for testing)

    Returns:
        Tuple of (status message, dict of character descriptions)
    """
    from pathlib import Path
    from openai import OpenAI

    chapters_path = Path(output_dir)

    # Load characters from characters.json or extract from map files
    if os.path.exists(characters_file):
        characters = load_characters(characters_file)
        if verbose:
            print(f"Loaded {len(characters)} characters from {characters_file}")
    else:
        # Try to extract characters from map files in the output_dir
        if chapters_path.is_dir():
            characters = get_characters_from_map_files(chapters_path)
            if verbose:
                print(f"Extracted {len(characters)} characters from map files in {output_dir}")
        else:
            if verbose:
                print(f"Characters file not found: {characters_file}", file=sys.stderr)
            return "No characters found.", {}

    if not characters:
        if verbose:
            print("No characters found.", file=sys.stderr)
        return "No characters found.", {}

    # Note: We do NOT filter out seed characters here. Seed characters will still be
    # described by the LLM (using their actual character names from the book), but
    # voice samples will not be generated for them (handled in generate_voice_samples).
    # This ensures that character descriptions are generated for all characters, not just
    # the ones without seed voices.

    if single_character:
        if single_character not in characters:
            if verbose:
                print(f"Character '{single_character}' not found.", file=sys.stderr)
            return f"Character '{single_character}' not found.", {}
        characters = [single_character]

    # Load chapter texts for context (with caching)
    chapters_dir_path = Path(chapters_dir)
    if chapters_dir_path.is_dir():
        chapter_texts, chapter_files = load_chapter_texts(chapters_dir_path)
        if verbose:
            print(f"Loaded {len(chapter_texts)} chapter files for context")
    else:
        chapter_texts, chapter_files = [], []

    # Initialize client
    if client is None:
        client = get_llm_client(api_key or LLM_SETTINGS["api_key"], port or LLM_SETTINGS["port"])

    # Resolve model at call time (not import time)
    if model is None:
        model = LLM_SETTINGS["default_model"]

    # Use shared logic
    descriptions = describe_characters_shared(
        characters=characters,
        chapter_texts=chapter_texts,
        chapter_files=chapter_files,
        output_dir=output_dir,
        client=client,
        model=model,
        wiki_url_template=wiki_url_template,
        verbose=verbose,
        progress_callback=progress_callback,
        voice_engine=voice_engine,
        max_concurrent=max_concurrent
    )

    result_msg = f"Successfully described {len(descriptions)} characters."
    return result_msg, descriptions


# Backward compatibility alias
describe_characters_in_dir = describe_characters